#!/bin/bash
dotnet tool install --global dotnet-ef
export PATH="$PATH:/root/.dotnet/tools"
dotnet ef database update --no-build
ls -la 
ls -la /app/
cd /app/build
dotnet run "project-foodie.dll" --urls "http://0.0.0.0:5000"